name: qmbs-scar
channels:
  - conda-forge
  - weinbe58
dependencies:
  - python=3.11
  - quspin            # conda channel weinbe58 has prebuilt binaries
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip
  - pip:
    - streamlit>=1.36
    - qiskit
    - pylatexenc
    - plotly